function [tableBackTestingVar, tableBackTestingVarDin]  = ...
    doBacktestingVAR(startDate, endDate, model, path, varargin)

% [tableBackTestingVar,tableBackTestingVarDin]  = ...
%     doBacktestingVAR(startDate, endDate, model, path, varargin)

% this code calculates a backtesting of the "static" and "dynamic"
% VaR obtained from the model (specified as input)
% first, obtain a backtesting of the estatic VaR at 95% and 99%
% with real returns and simulated returns (with model specified)
% second, obtain a backtesting of the dynamic VaR at 95% and 99%
% with real returns and simulated returns (with model specified)
% varargin determine the tickers that we want in the analysis
% iniDate and endDate are the point in time date that we
% want to start and finish with in the analysis
% requires a path folder, the folder path where the files are saved
% finally we obtain as output tableBackTestingVar and
% tableBackTestingVarDin, two structure array
% with all backtesting Var calculated from the financial series
% with static Var and dinamic Var, respectevely.
% try, for exmaple:
% model = {'BrowG', 'MJDM', 'VG', 'HAW'};
% [BcktTableVar, BckTableVarDin]  = doBacktestingVAR('01012014', ...
%     '01012018', model, 'C:\Users\Desktop\Matlab', '^GSPC',...
%     '^IBEX', '^GDAXI', '^IXIC', '000001.SS', 'BNP.PA', ...
%     'BAC', 'BBVA.MC', 'HSBC', 'SMFG');
% warning, we have a list of tickers  but maybe
% this list need to be updated, we included in the code an
% error message when the ticker is missed: the ticker and
% the name of the variable is required in the ftick variable.

% check folder
if ~exist(path, 'dir')
    mkdir(path)
end


% list (maybe this list need to be updated with the ticker
% and name required)

ftick = {'^GSPC', 'SP500';...
    '^IBEX', 'IBEX35';...
    '^FCHI', 'CAC40';...
    '^FTSE', 'FTSE100';...
    '^N225', 'Nikkei225';...
    '000001.SS', 'SSECompInd';...
    'BAC', 'BankAmer';...
    'C', 'Citigroup';...
    'GS', 'GoldmanSachs';...
    'JPM', 'JPMorgCh';...
    'MS', 'MorgStanl';...
    'BBVA.MC', 'BBVA';...
    'SAN', 'Santander';...
    'CABK.MC', 'Caixabank';...
    'SAB.MC', 'Sabadell';...
    'BNP.PA', 'BNP';...
    'ACA.PA', 'CreditAgricole';...
    'GLE.PA', 'SocieteGenerale';...
    'HSBC', 'HSBC';...
    'BARC.L', 'Barclays';...
    'LLOY.L', 'Lloyds';...
    'RBS.L', 'RoyalBankScot';...
    'MTU', 'MitsubishiBank';...
    'SMFG', 'SumitoBank';...
    'MFG', 'MizuhoBank';...
    '601398.SS', 'ICBC';...
    '601939.SS', 'CBC';...
    '601288.SS', 'ABC';...
    '^GDAXI', 'DAX';...
    '^IXIC', 'NASDAQ';...
    'MSFT', 'Microsoft';...
    'AMZN', 'Amazon';...
    'APPL', 'Apple';...
    'GOOG', 'Google';...
    'PG', 'Proct&Gamb';...
    'BA', 'Boing';
    };

% download the data
if iscell(varargin)
    dtick = varargin{1,:};
else
    dtick = varargin;
end

idx = ismember(ftick, dtick);
rtick = ftick(idx(:, 1), :);
dtick2 = rtick(:, 1);
% error message if we need to update the ftick list
if size(dtick2, 1) ~= size(dtick,2)
    missedTickersloc = ismember(dtick, dtick2);
    missedTickers = strjoin(dtick(~missedTickersloc), ', ');
    error(['There are missed tickers. Consider update the list ',...
        'ftick in the code with the following tickers: ', ...
        missedTickers])
end

m = size(dtick2, 1);
n = size(model, 2);
pv = [0.05 0.01];

%BACKTESTING 'Estatic' VAR
for i = 1 : m
    % read the xls files
    for j = 1 : n
        tickname = dtick2(i);
        disp(['Reading Prices from ', char(string(rtick(i, 2))),...
            ' in ', datestr(datetime(startDate, 'InputFormat',...
            'ddMMyyyy'), 'dd-mm-yyyy'),' to ', ...
            datestr(datetime(endDate,...
            'InputFormat','ddMMyyyy'), 'dd-mm-yyyy')])
        % catch returns
        ret = readtable([path, char(string(rtick(i, 2))), ...
            '_PricesRealSimul_', ...
            char(string(model(1, j))),'_',...
            datestr(datetime(startDate,'InputFormat',...
            'ddMMyyyy'), 'ddmmyyyy'), ' to ', ...
            datestr(datetime(endDate, 'InputFormat', 'ddMMyyyy'),...
            'ddmmyyyy'), '.xls'], 'Sheet', 1);
        R(i, j).ret = ret;
        % catch VAR/ES
        VARES = readtable([path, char(string(rtick(i, 2))), ...
            '_VARESRealSimul_',...
            char(string(model(1, j))),'_',...
            datestr(datetime(startDate,'InputFormat',...
            'ddMMyyyy'), 'ddmmyyyy'), ' to ', ...
            datestr(datetime(endDate, 'InputFormat', 'ddMMyyyy'),...
            'ddmmyyyy'), '.xls'], 'Sheet', 1);
        V(i, j).VARES = VARES;
        
        % real returns
        R(i, j).ret.Properties.VariableNames(3) = {'Real_Returns'};
        ret.Properties.VariableNames(3) = {'Real_Returns'};
        rettobacktest = R(i, j).ret.Real_Returns;
        
        % var 95 and 99
        v95 = V(1).VARES.VAR95(1);
        v99 = V(1).VARES.VAR99(1);
        
        % backtesting
        disp(['Backtesting Var with real returns from ',...
            char(string(rtick(i, 2))),...
            ' model ', char(string(model(1, j))),...
            ' in ', datestr(datetime(startDate, 'InputFormat',...
            'ddMMyyyy'), 'dd-mm-yyyy'),' to ',...
            datestr(datetime(endDate,...
            'InputFormat','ddMMyyyy'), 'dd-mm-yyyy')])
        
        % using 95%
        tV95 = bcktsting(rettobacktest, v95, pv(1), tickname,...
            ftick, 1, model(1, j), 0, 0);
        tableBackTestingVar(i, j).V95R = tV95;
        
        % save it in a xls file
        Excel = actxserver('Excel.Application');
        writetable(tV95, [path, char(string(rtick(i, 2))),...
            '_VARBckTst95.xls'], 'Sheet', 1, 'WriteRowNames', 1)
        excelWorkbook = Excel.workbooks.Open([path,...
            char(string(rtick(i, 2))), '_VARBckTst95.xls']);
        Excel.Worksheets.Item(1).Name = ...
            [char(string(rtick(i, 2))), '_V95rr'];
        Excel.ActiveWorkbook.Save();
        % Close the workbook.
        excelWorkbook.Close(false);
        % Shut down Excel.
        Excel.Quit;
        
        % using 99%
        tV99 = bcktsting(rettobacktest, v99, pv(2), tickname,...
            ftick, 1, model(1, j), 0, 0);
        tableBackTestingVar(i, j).V99R = tV99;
        
        % save it in a xls file
        Excel = actxserver('Excel.Application');
        writetable(tV99, [path, char(string(rtick(i, 2))),...
            '_VARBckTst99.xls'], 'Sheet',1, 'WriteRowNames', 1)
        excelWorkbook = Excel.workbooks.Open([path,...
            char(string(rtick(i, 2))),  '_VARBckTst99.xls']);
        Excel.Worksheets.Item(1).Name = ...
            [char(string(rtick(i, 2))),'_V99rr'];
        Excel.ActiveWorkbook.Save();
        % Close the workbook.
        excelWorkbook.Close(false);
        % Shut down Excel.
        Excel.Quit;
        
        disp(['Backtesting Var with  simulated returns from ',...
            char(string(rtick(i, 2))),...
            ', model ', char(string(model(1, j))),...
            ' in ', datestr(datetime(startDate, 'InputFormat',...
            'ddMMyyyy'), 'dd-mm-yyyy'),' to ',...
            datestr(datetime(endDate,...
            'InputFormat','ddMMyyyy'), 'dd-mm-yyyy')])
        
        % simulated returns
        R(i, j).ret.Properties.VariableNames(4) = ...
            {'Simulated_Returns'};
        ret.Properties.VariableNames(4) = {'Simulated_Returns'};
        rettobacktests = R(i, j).ret.Simulated_Returns;
        % var at 95% and 99%
        v95s = V(i, j).VARES.VAR95(2);
        v99s = V(i, j).VARES.VAR99(2);
        
        % backtesting at 95%
        tV95s = bcktsting2dv(rettobacktests, v95s, pv(1), tickname,...
            ftick, 0, model(1, j), 0, 0);
        tableBackTestingVar(i, j).V95S = tV95s;
        
        % save it in a xls file
        Excel = actxserver('Excel.Application');
        writetable(tV95s, [path, char(string(rtick(i, 2))),...
            '_VARBckTst95_',char(string(model(1, j))),'.xls'],...
            'Sheet', j + 1, 'WriteRowNames', 1)
        excelWorkbook = Excel.workbooks.Open([path,...
            char(string(rtick(i, 2))), '_VARBckTst95_', ...
            char(string(model(1, j))),'.xls']);
        Excel.Worksheets.Item(j + 1).Name = ...
            [char(string(rtick(i, 2))),...
            '_V95rs_', char(string(model(1, j)))];
        Excel.ActiveWorkbook.Save();
        % Close the workbook.
        excelWorkbook.Close(false);
        % Shut down Excel.
        Excel.Quit;
        
        % at 99%
        tV99s = bcktsting2dv(rettobacktests, v99s, pv(2), tickname,...
            ftick, 0, model(1, j), 0, 0);
        tableBackTestingVar(i, j).V99S = tV99s;
        
        % save it in a xls file
        Excel = actxserver('Excel.Application');
        writetable(tV99s, [path, char(string(rtick(i, 2))), ...
            '_VARBckTst99_', char(string(model(1, j))),'.xls'],...
            'Sheet', j + 1, 'WriteRowNames', 1)
        excelWorkbook = Excel.workbooks.Open([path,...
            char(string(rtick(i, 2))), '_VARBckTst99_',...
            char(string(model(1, j))),'.xls']);
        Excel.Worksheets.Item(j + 1).Name = ...
            [char(string(rtick(i, 2))),...
            '_V99rs_', char(string(model(1, j)))];
        Excel.ActiveWorkbook.Save();
        % Close the workbook.
        excelWorkbook.Close(false);
        % Shut down Excel.
        Excel.Quit
    end
end

% BACKTESTING Dynamic VAR
for i = 1:m
    %  read the xls
    for j = 1:n
        tickname = dtick2(i);
        ret = readtable([path, char(string(rtick(i, 2))), ...
            '_PricesRealSimul_', ...
            char(string(model(1, j))),'_',...
            datestr(datetime(startDate,'InputFormat',...
            'ddMMyyyy'), 'ddmmyyyy'), ' to ', ...
            datestr(datetime(endDate, 'InputFormat', 'ddMMyyyy'),...
            'ddmmyyyy'), '.xls'], 'Sheet', 1);
        R(i, j).ret = ret;
        % read sheets in the xls
        [~,ShN] = xlsfinfo([path, char(string(rtick(i, 2))),...
            '_VARESRealSimul_', char(string(model(1, j))),'_',...
            datestr(datetime(startDate,'InputFormat',...
            'ddMMyyyy'), 'ddmmyyyy'), ' to ', ...
            datestr(datetime(endDate, 'InputFormat', 'ddMMyyyy'),...
            'ddmmyyyy'), '.xls']);
        msh = length(ShN);
        for k = 1 : msh
            Name = ShN{k};
            V = readtable([path, char(string(rtick(i, 2))),...
                '_VARESRealSimul_',...
                char(string(model(1, j))),'_',...
                datestr(datetime(startDate,'InputFormat',...
                'ddMMyyyy'), 'ddmmyyyy'), ' to ', ...
                datestr(datetime(endDate, 'InputFormat', ...
                'ddMMyyyy'), 'ddmmyyyy'), '.xls'],'Sheet',Name);
            VAR(k).Name = Name;
            VAR(k).V = V;
        end
        
        % loop for every method - real returns
        for h = 2:2:msh - 1
            
            if isempty(VAR(h).V)
                h = 2 + h ;
            end
            
            % catch method
            splitname = split(VAR(h).Name,"_");
            fullmethod = char(splitname(2));
            method = fullmethod(1:4);
            % real returns and dynamic VaR
            R(i, j).ret.Properties.VariableNames(3) = ...
                {'Real_Returns'};
            rettobacktest = R(i, j).ret.Real_Returns;
            % select Var for every method
            if sum(strcmp(method, 'PVAR'))
                if sum(strcmp(model(1, j), 'BrowG'))
                    v95 = [VAR(h).V.VN95 VAR(h).V.t95];
                else
                    v95 = VAR(h).V.V95;
                end
            elseif sum(strcmp(method, 'EWMA'))
                v95 = [VAR(h).V.EWMA95 VAR(h).V.EWMAt95];
            elseif sum(strcmp(method, 'HIST'))
                v95 = VAR(h).V.H95;
            else
                v95 = [VAR(h).V.CFVN95 VAR(h).V.CFVT95];
            end
            
            % backtesting
            disp(['Backtesting "dynamic" Var with real returns',...
                ' from ', char(string(rtick(i, 2))),', model ', ...
                char(string(model(1, j))),...
                ' and method ', char(string(method)), ' in ', ...
                datestr(datetime(startDate, 'InputFormat',...
                'ddMMyyyy'), 'dd-mm-yyyy'),' to ',...
                datestr(datetime(endDate,...
                'InputFormat','ddMMyyyy'), 'dd-mm-yyyy')])
            
            window = size(rettobacktest,1) - size(v95,1);
            tVD95 = bcktsting2dv(rettobacktest(window + 1 : end),...
                v95, pv(1), tickname, ftick, 1, ...
                model(1, j), 1, method);
            tableBackTestingVarDin(i, j).VD95R = tVD95;
            
            writetable(tVD95, [path, char(string(rtick(i, 2))),...
                '_VARBckTst95_',...
                char(string(method)),'.xls'],...
                'Sheet',j + 1, 'WriteRowNames', 1)
            
            excelWorkbook = Excel.workbooks.Open([path,...
                char(string(rtick(i, 2))), '_VARBckTst95_',...
                char(string(method)),'.xls']);
            Excel.Worksheets.Item(j + 1).Name = ...
                [char(string(rtick(i, 2))),...
                '_VD95rr_',char(string(method)),'_',...
                char(string(model(1, j)))];
            Excel.ActiveWorkbook.Save();
            % Close the workbook.
            excelWorkbook.Close(false);
            % Shut down Excel.
            Excel.Quit;
            
           % select Var for every method
            if sum(strcmp(method, 'PVAR'))
                if sum(strcmp(model(1, j), 'BrowG'))
                    v99 = [VAR(h).V.VN99 VAR(h).V.t99];
                else
                    v99 = VAR(h).V.V99;
                end
            elseif sum(strcmp(method, 'EWMA'))
                v99 = [VAR(h).V.EWMA99 VAR(h).V.EWMAt99];
            elseif sum(strcmp(method, 'HIST'))
                v99 = VAR(h).V.H99;
            end
            
            % backtesting at 99%
            tVD99 = bcktsting2dv(rettobacktest(window + 1 : end),...
                v99, pv(2), tickname, ftick, 1, ...
                model(1, j), 1, method);
            tableBackTestingVarDin(i, j).VD99R = tVD99;
            
            writetable(tVD99, [path, char(string(rtick(i, 2))),...
                '_VARBckTst99_', char(string(method)),'.xls'],...
                'Sheet',j + 1, 'WriteRowNames', 1)
            excelWorkbook = Excel.workbooks.Open([path,...
                char(string(rtick(i, 2))), '_VARBckTst99_',...
                char(string(method)),'.xls']);
            Excel.Worksheets.Item(j + 1).Name = ...
                [char(string(rtick(i, 2))),...
                '_VD99rr_',char(string(method)),'_',...
                char(string(model(1, j)))];
            Excel.ActiveWorkbook.Save();
            % Close the workbook.
            excelWorkbook.Close(false);
            % Shut down Excel.
            Excel.Quit;
        end
        
        % loop for every method - simulated returns
        for h = 3:2:msh
            
            if isempty(VAR(h).V)
                h = 2 + h;
            end
            
            % catch method
            splitname = split(VAR(h).Name,"_");
            fullmethod = char(splitname(2));
            method = fullmethod(1:4);
            % simulated returns and dynamic var
            R(i, j).ret.Properties.VariableNames(4) = ...
                {'Simulated_Returns'};
            rettobacktest = R(i, j).ret.Simulated_Returns;
            
            % catch Var for every method
            if sum(strcmp(method, 'PVAR'))
                if sum(strcmp(model(1, j), 'BrowG'))
                    v95 = [VAR(h).V.VN95 VAR(h).V.t95];
                else
                    v95 = VAR(h).V.V95;
                end
            elseif sum(strcmp(method, 'EWMA'))
                v95 = [VAR(h).V.EWMA95 VAR(h).V.EWMAt95];
            elseif sum(strcmp(method, 'HIST'))
                v95 = VAR(h).V.H95;
            else
                v95 = [VAR(h).V.CFVN95 VAR(h).V.CFVT95];
            end
            
            disp(['Backtesting "dynamic" Var with simulated',...
                ' returns from ', char(string(rtick(i, 2))),...
                ', model ', char(string(model(1, j))),...
                ' and method ', char(string(method)), ' in ', ...
                datestr(datetime(startDate, 'InputFormat',...
                'ddMMyyyy'), 'dd-mm-yyyy'),' to ',...
                datestr(datetime(endDate,...
                'InputFormat','ddMMyyyy'), 'dd-mm-yyyy')])
            
            % backtesting at 95%
            window = size(rettobacktest,1) - size(v95,1);
            tVD95S = bcktsting2dv(rettobacktest(window + 1 : end),...
                v95, pv(1),tickname, ftick,...
                0, model(1, j), 1, method);
            tableBackTestingVarDin(i, j).VD95S = tVD95S;
            
            writetable(tVD95S, [path, char(string(rtick(i, 2))),...
                '_VARBckTst95_', char(string(method)),'_',...
                char(string(model(1, j))),'.xls'],...
                'Sheet',j + 1, 'WriteRowNames', 1)
            excelWorkbook = Excel.workbooks.Open([path,...
                char(string(rtick(i, 2))), '_VARBckTst95_',...
                char(string(method)),'_'...
                char(string(model(1, j))),'.xls']);
            Excel.Worksheets.Item(j + 1).Name = ...
                [char(string(rtick(i, 2))),...
                '_VD95rs_',char(string(method)),'_',...
                char(string(model(1, j)))];
            Excel.ActiveWorkbook.Save();
            % Close the workbook.
            excelWorkbook.Close(false);
            % Shut down Excel.
            Excel.Quit;
            
           if sum(strcmp(method, 'PVAR'))
                if sum(strcmp(model(1, j), 'BrowG'))
                    v99 = [VAR(h).V.VN99 VAR(h).V.t99];
                else
                    v99 = VAR(h).V.V99;
                end
            elseif sum(strcmp(method, 'EWMA'))
                v99 = [VAR(h).V.EWMA99 VAR(h).V.EWMAt99];
            elseif sum(strcmp(method, 'HIST'))
                v99 = VAR(h).V.H99;
            end
            
            % backtesting at 99%
            tVD99S = bcktsting2dv(rettobacktest(window + 1 : end),...
                v99, pv(2), tickname, ftick, 0, ...
                model(1, j), 1, method);
            tableBackTestingVarDin(i, j).VD99S = tVD99S;
            writetable(tVD99S, [path, char(string(rtick(i, 2))),...
                '_VARBckTst99_',...
                char(string(method)),...
                '_',char(string(model(1, j))),'.xls'],...
                'Sheet',j + 1, 'WriteRowNames', 1)
            excelWorkbook = Excel.workbooks.Open([path,...
                char(string(rtick(i, 2))), '_VARBckTst99_',...
                char(string(method)),'_'...
                char(string(model(1, j))),'.xls']);
            Excel.Worksheets.Item(j + 1).Name = ...
                [char(string(rtick(i, 2))),...
                '_VD99rs_',char(string(method)),'_',...
                char(string(model(1, j)))];
            Excel.ActiveWorkbook.Save();
            % Close the workbook.
            excelWorkbook.Close(false);
            % Shut down Excel.
            Excel.Quit;
        end
    end
end
end